version: '3'

services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=noteappdb
        ports:
            - "5432:5432"

